### PR TITLE
Replace use of order number (UID) with the much more human friendly o…

### PR DESCRIPTION
**Pull request by bossanova808**
…rder reference (which is how business folks will refer to orders, and it is business folks that will use analytics data one presumes.  Note the reference falls back to the old order-number automatically if a custom reference format is not set, anyway, so for those not using friendly reference numbers behaviour will not change anyway.

### CODE REVIEW

**Comment by bossanova808** [comment]
Any chance you'd merge this in the near future?  Now I have live data flowing from this, I'd really rather see proper order numbers than commerce's irritating UID things...

**Comment by bossanova808** [comment]
(or if not, provide an event before submission where we can modify the data?)

**Comment by khalwat** [comment]
Wow sorry I missed this @bossanova808 -- will get it merged.

**Comment by bossanova808** [comment]
No worries Andrew, I know you're a busy guy!!

**Pull request merged**
